### ISSUE TITLE
How to get OpenRobertaUSBNXT working on arm / RasPi? 

### ISSUE THREAD

**Issue by othreed** [OpenRoberta/robertalab-usbprogram-nxt#8]
Hi,
We have the Pi4 with Raspian Buster as classroom computers and would like get our old NXTs to work with Open-Roberta on them.

Would it be possible to get the usbprogram-nxt to run on the Raspberry Pi?
I have the following Java Version:
`openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-post-Raspbian-5)
OpenJDK Server VM (build 11.0.3+7-post-Raspbian-5, mixed mode)`

I created the correct udev rules and lsusb shows the NXT:
`Bus 001 Device 005: ID 0694:0002 Lego Group Mindstorms NXT`

I am able to start the OpenRobertaUSBNXT.jar on Raspbian but I get the following error message:
`java -jar -Dfile.encoding=utf-8 OpenRobertaUSBNXT.jar 
12/03/2020 09:21:16.336 - [de.fhg.iais.roberta.usb.Main.configureLogger] - [INFO] - Logging to file: /home/teacher/OpenRobertaUSBNXT/OpenRobertaUSBNXT.log
12/03/2020 09:21:17.149 - [de.fhg.iais.roberta.usb.Main$1.getLocals] - [CONFIG] - Language en
OpenJDK Server VM warning: You have loaded library /tmp/libjlibnxt7886706344558147127.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Mar 12, 2020 9:21:19 AM lejos.pc.comm.NXTConnector search
SEVERE: Error: Failed to load USB comms driver. lejos.pc.comm.NXTCommException: lejos.pc.comm.NXTCommException: Cannot load NXTComm driver
`

Any help is much appreciated
:)

**Comment by boonto** [comment]
Can you try [USBProgramNXT.zip](https://github.com/OpenRoberta/robertalab-usbprogram-nxt/files/4325017/USBProgramNXT.zip)? We had similar issues previously and this version helped.

**Comment by othreed** [comment]
I tried it but I still get the error.
This is the output on the terminal after closing the program:
`ar 13, 2020 7:35:17 AM lejos.pc.comm.NXTConnector search
SEVERE: Error: Failed to load USB comms driver. lejos.pc.comm.NXTCommException: lejos.pc.comm.NXTCommException: Cannot load NXTComm driver
Exception in thread "main" java.lang.IllegalStateException: Shutdown in progress
	at java.base/java.io.DeleteOnExitHook.add(DeleteOnExitHook.java:61)
	at java.base/java.io.File.deleteOnExit(File.java:1091)
	at de.fhg.iais.roberta.util.NativeUtils.loadLibraryFromJar(NativeUtils.java:84)
	at lejos.internal.jni.JNILoader.loadLibrary(JNILoader.java:35)
	at lejos.pc.comm.NXTCommLibnxt.initialize0(NXTCommLibnxt.java:70)
	at lejos.pc.comm.NXTCommLibnxt.initialize(NXTCommLibnxt.java:77)
	at lejos.pc.comm.NXTCommFactory.newNXTCommInstance(NXTCommFactory.java:104)
	at lejos.pc.comm.NXTCommFactory.createNXTComm(NXTCommFactory.java:78)
	at lejos.pc.comm.NXTConnector.search(NXTConnector.java:35)
	at de.fhg.iais.roberta.connection.NXTCommunicator.discover(NXTCommunicator.java:63)
	at de.fhg.iais.roberta.connection.NXTUSBBTConnector$DiscoverNXT.discover(NXTUSBBTConnector.java:274)
	at de.fhg.iais.roberta.connection.NXTUSBBTConnector.findRobot(NXTUSBBTConnector.java:40)
	at de.fhg.iais.roberta.usb.Main.main(Main.java:94)
`

**Comment by boonto** [comment]
Thanks! In that case I'll have to do some more investigating, stay tuned.

**Comment by othreed** [comment]
I was able to compile and install leJOS_NXJ_0.9.1beta-3 using this tutorial: http://stefanshacks.blogspot.com/2015/03/lejos-on-raspberry-pi-including-usb-and.html
LeJOS works and I can use USB to connect the NXT to my raspberry pi and e.g. use nxjcontrol and others.
Getting the NXTUSB and hence Open Roberta running on the raspberry would allow us to offer a nice differentiation in our IT curriculum.

**Comment by boonto** [comment]
Rebuilding the jlibnxt lib for Raspberry seems to fix the first problem, now the driver can be loaded.
However, I still get the greyed out connect button mentioned in some other issues which results from the JLIBNXT library when trying to establish the connection.

**Comment by othreed** [comment]
Any ideas on how to fix it?
Now that the schools are closed due to the pandemic outbreak I have some time to work on our Setup and our Curriculum.
:)

**Comment by boonto** [comment]
Not yet, I am working on it from time to time but progress is unfortunately very slow, as these low level usb issues are not really my area.

**Comment by othreed** [comment]
@boonto,
if the problem lies in JLIBNXT and several linux distribution have problems with it, could we somehow help to solve this? 
Do you know where to problem is situated?

**Comment by boonto** [comment]
I haven't looked into it for a while, I think the error occurs in the `usb_open` called [here](https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/libnxt/jlibnxt.c#l140) when using a kernel version > 4.15. It also has something to do with the version of `libusb-0.1-4`, whether it's the compat version or not.
We will gladly accept any help or further investigation into it.

**Comment by catedrastics** [comment]
I installed OpenRobertaUsbNxt on RasberryPi 400. In the process it told me that i386 architecture is not available for this system. Everything installed, but it does not activate the button to connect the NXT. But the same if it is recognized by the system, since I can download the program directly with the nbc compiler.
Please help with this, check the version of OpenRobertaUsbNxt again and adjust its full compatibility with Rasbian, which no longer supports i386 architecture.
In Venezuela we have more than 45 schools that have Lego NXT and also RCX. OpenRoberta is an excellent option to continue programming with these devices. They already let the RCX die, it does not give it a connection, nor does it support Open-Roberta. I hope it's not the same with NXT. The same Lego company released new software that does not recognize NXT devices.
I hope we can support this cause. If you need help, count on me. I'm no Java expert, but willing to help.
Alejandro Del Mar adelmar@ucab.edu.ve

**Comment by catedrastics** [comment]
This is the message after installation
------
iea@raspberrypi:~/OpenRobertaUSBNXT $ sudo sh install.sh
Obj:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease      
Obj:2 http://archive.raspberrypi.org/debian bullseye InRelease         
Leyendo lista de paquetes... Hecho
N: Omitiendo el uso del fichero configurado «main/binary-i386/Packages» ya que el repositorio «http://raspbian.raspberrypi.org/raspbian bullseye InRelease» no admite la arquitectura «i386»
N: Omitiendo el uso del fichero configurado «contrib/binary-i386/Packages» ya que el repositorio «http://raspbian.raspberrypi.org/raspbian bullseye InRelease» no admite la arquitectura «i386»
N: Omitiendo el uso del fichero configurado «non-free/binary-i386/Packages» ya que el repositorio «http://raspbian.raspberrypi.org/raspbian bullseye InRelease» no admite la arquitectura «i386»
N: Omitiendo el uso del fichero configurado «rpi/binary-i386/Packages» ya que el repositorio «http://raspbian.raspberrypi.org/raspbian bullseye InRelease» no admite la arquitectura «i386»
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias... Hecho
Leyendo la información de estado... Hecho
El paquete libc6-i386 no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente

El paquete libxext6:i386 no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente

El paquete libxi6:i386 no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente

El paquete libxrender1:i386 no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente

El paquete libxtst6:i386 no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente

E: El paquete «libc6-i386» no tiene un candidato para la instalación
E: El paquete «libxext6:i386» no tiene un candidato para la instalación
E: El paquete «libxrender1:i386» no tiene un candidato para la instalación
E: El paquete «libxtst6:i386» no tiene un candidato para la instalación
E: El paquete «libxi6:i386» no tiene un candidato para la instalación
E: No se ha podido localizar el paquete libusb-0.1-4:i386
E: No se pudo encontrar ningún paquete usando «*» con «libusb-0.1-4»
E: No se pudo encontrar ningún paquete con la expresión regular «libusb-0.1-4»
/etc/udev/rules.d/70-lego.rules found.
groupadd: el grupo «lego» ya existe
Añadiendo al usuario iea al grupo lego
Añadiendo al usuario iea al grupo dialout

------
